"""add transcript to meetings

Revision ID: 1dff68835dbe
Revises: 9660f4aec51d
Create Date: 2026-03-16 19:50:54.394993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dff68835dbe'
down_revision: Union[str, Sequence[str], None] = '9660f4aec51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('transcript', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'transcript')
    # ### end Alembic commands ###
