"""create meeting_access table

Revision ID: 7521c5865584
Revises: 076c9c48667b
Create Date: 2026-02-26 11:28:35.955993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7521c5865584'
down_revision: Union[str, Sequence[str], None] = '076c9c48667b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('shared_email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'shared_email', name='uq_meeting_access_meeting_email')
    )
    op.create_index(op.f('ix_meeting_access_meeting_id'), 'meeting_access', ['meeting_id'], unique=False)
    op.create_index('ix_meeting_access_shared_email', 'meeting_access', ['shared_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_meeting_access_shared_email', table_name='meeting_access')
    op.drop_index(op.f('ix_meeting_access_meeting_id'), table_name='meeting_access')
    op.drop_table('meeting_access')
    # ### end Alembic commands ###
