"""add audio_url to meetings

Revision ID: 9660f4aec51d
Revises: 30238738cdc5
Create Date: 2026-03-12 17:00:02.054578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9660f4aec51d'
down_revision: Union[str, Sequence[str], None] = '30238738cdc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('audio_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'audio_url')
    # ### end Alembic commands ###
